### ISSUE TITLE
Proposal: createReducer should throw error if an action type is undefined

### ISSUE THREAD

**Issue by MrOrz** [PlatziDev/redux-duck#2]
## Scenario
I was re-using an action type from another duck, and a weird bug stuck me:

```js
// duck-a.js
import { SOME_ACTION_TYPE } from './duck-b'
// ... some other stuff ...
createReducer({
  [SOME_ACTION_TYPE]: (state, action) => console.log('Reducer in A') || state;
});
```

```js
// duck-b.js
const duck = createDuck('b');
// ... some other stuff ...
export const SOME_ACTION_TYPE = duck.defineType('SOME_ACTION_TYPE');
export const someAction = duck.createAction(SOME_ACTION_TYPE)
createReducer({
  [SOME_ACTION_TYPE]: (state, action) => console.log('Reducer in B') || state
});
```

When I dispatch `someAction`, the reducer in B is invoked, but not the reducer in A.

After spending hours I found that I was importing something from `duck-a` to `duck-b` as well, causing a circular dependency between `duck-a` and `duck-b`, which makes the imported `SOME_ACTION_TYPE` becomes `undefined`.

## Proposal

Although the circular dependency is entirely my fault, I think `createReducer` can help me spot the circular dependency if **`createReducer` can throw error when `undefined` is one of the object key**.

**Comment by sergiodxa** [comment]
Would you mind moving this issue to https://github.com/sergiodxa/redux-duck/issues?

I recently recovered the package and started maintaining it again since @PlatziDev was not doing it and I would like to work on this.

**Comment by MrOrz** [comment]
@sergiodxa  Sure :) can you move it or do I need to move it myself?

**Comment by sergiodxa** [comment]
I can’t use the transfer issue feature, I could copy and paste it if you prefer but you will not be notified when I close the issue

**Comment by MrOrz** [comment]
Done :) closing here
